services:
  brics:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: brics_postgres
    image: postgres:latest
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - brics-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  # minio:
  #   container_name: brics-minio
  #   image: minio/minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   volumes:
  #     - brics-minio-storage:/data
  #   env_file:
  #   environment:
  #     MINIO_ROOT_USER: ${POSTGRES_USER}
  #     MINIO_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
  #     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  #     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  #   command: server --console-address ":9001" /data

volumes:
  brics-pgdata:
  # brics-minio-storage:
