services:
  brics:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    environment:
      TRON_FULL_NODE: http://172.17.0.1:8090
      TRON_SOLIDITY_NODE: http://172.17.0.1:8090
      TRON_EVENT_SERVER: http://172.17.0.1:8090
      USDT_RPC_URL: http://172.17.0.1:8090
    ports:
      - 8000:8000
    depends_on:
      - postgres
    secrets:
      - usdt_treasury_private_key
      - usdt_webhook_secret
    networks:
      - postgres

  postgres:
    container_name: brics_postgres
    image: postgres:latest
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

volumes:
  postgres_data:

secrets:
  usdt_treasury_private_key:
    file: ./secrets/usdt_treasury_private_key
  usdt_webhook_secret:
    file: ./secrets/usdt_webhook_secret

networks:
  postgres:
    driver: bridge
