services:
  brics:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: brics_postgres
    image: postgres:latest
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
