ALTER TYPE "TariffOperation" ADD VALUE IF NOT EXISTS 'SOM_TO_ESOM';
ALTER TYPE "TariffOperation" ADD VALUE IF NOT EXISTS 'ESOM_TO_SOM';
ALTER TYPE "TariffOperation" ADD VALUE IF NOT EXISTS 'USDT_TRC20_TO_ESOM';
